config/routes.rb
Chess01::Application.routes.draw do
  devise_for :users

  root 'games#index'
  resources :games

end

app/models/bishop.rb
class Bishop < Piece

end

app/models/game.rb
class Game < ActiveRecord::Base
	has_many :pieces

end

app/models/king.rb
class King < Piece

end

app/models/knight.rb
class Knight < Piece

end

app/models/pawn.rb
class Pawn < Piece

end

app/models/piece.rb
class Piece < ActiveRecord::Base
	belongs_to :game
end

app/models/queen.rb
class Queen < Piece

end

app/models/rook.rb
class Rook < Piece

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	def index
	end

	def new
		@game = Game.new
	end

	def create
		@game = Game.create(game_params)
		redirect_to game_path(@game)
	end

	private

	def game_params
		params.require(:game).permit(:white_player_id, :black_player_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<h1>Home Page</h1>
<br />
<div id="render_table"></div>

<div class="test"></div>

<h2>To Do</h1>
<form name="check_list_form">
	<input type="text" name="check_list_item"/>
</form>
<div id="button">Add!</div>
<br />
<div class="list"></div>
<br />
<div class="chessboard">

</div>


<br />
<%= link_to 'Play Chess!', new_game_path %>

app/views/games/new.html.erb
<h1>Start a new game</h1>
<br />
<%= simple_form_for @game do |f| %>
	<%= f.input :white_player_id %>
	<%= f.input :black_player_id %>
	<%= f.submit 'Start', :class => 'btn btn-primary' %>
<% end %>

app/views/games/show.html.erb
<h1>Game show page</h1>
<br />
<div class="containter">
	<table class="board" id="chessboard">
		<tbody>
			<% (1..8).each do |row_num| %>
				<tr>
					<% (1..8).each do |cell_num| %>
						<% id = row_num + cell_num %>
						<% if row_num % 2 == cell_num % 2 %>
							<td id="#{id}" class="white_sq ui-droppable">
								<% if row_num == 2 || row_num == 7 %>
									<%= image_tag 'pawn.png', class: "piece" %>
								<% end %>
							</td>
						<% else %>
							<td id="#{id}" class="dark_sq ui-droppable">
								<% if row_num == 2 || row_num == 7 %>
									<%= image_tag 'pawn.png', class: "piece" %>
								<% end %>
							</td>
						<% end %>
					<% end %>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chess01</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>